# .github/workflows/ci.yml
name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++  # Instala o compilador e o CMake

    - name: Install Google Test
      run: |
        # Baixa o GTest
        git clone https://github.com/google/googletest.git
        cd googletest
        mkdir build
        cd build
        cmake ..
        make
        sudo make install  # Instala GTest no sistema

    - name: Build project
      run: |
        mkdir -p build
        cd build
        cmake ..  # Assume que o CMakeLists.txt está no diretório raiz
        make

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure  # Executa testes usando CTest e mostra saídas de erros

    - name: Run Tests and Generate Report
      run: |
        mkdir -p reports
        ./build/runTests --gtest_output=xml:reports/test_results.xml
  
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: reports/test_results.xml
  
    - name: Publish Test Results to GitHub
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: Google Test
        path: reports/test_results.xml
        reporter: junit