name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true  # Baixa os submódulos, incluindo o Google Test

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake
        
      - name: Download and Build Google Test
        run: |
          git clone https://github.com/google/googletest.git
          mkdir -p googletest/build
          cd googletest/build
          cmake ..
          make
          sudo cp lib/*.a /usr/lib

      - name: Clean previous build cache
        run: rm -rf build
        
      - name: Create build directory
        run: mkdir -p build

      - name: Configure project
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build

      - name: Run tests
        run: cd build && ctest --output-on-failure
