# .github/workflows/ci.yml
name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++  # Instala o compilador e o CMake

    - name: Build project
      run: |
        mkdir -p build
        cd build
        cmake ..  # Assume que o CMakeLists.txt está no diretório raiz
        make

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure  # Executa testes usando CTest e mostra saídas de erros
